service: hywep-recruit-etl

plugins:
  - serverless-plugin-datadog

provider:
  name: aws
  runtime: nodejs20.x
  region: ap-northeast-2
  environment:
    RECRUIT_TABLE: ${self:custom.dynamoTableNames.${opt:stage, 'dev'}}
    DATADOG_API_KEY: ${env:DATADOG_API_KEY}
    DATADOG_APP_KEY: ${env:DATADOG_APP_KEY}
    DATADOG_SITE: ${env:DATADOG_SITE}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:GetObject
        - s3:PutObject
      Resource:
        - arn:aws:s3:::${self:custom.s3BucketNames.${opt:stage, 'dev'}}/*
    - Effect: Allow
      Action:
        - dynamodb:PutItem
        - dynamodb:BatchWriteItem
        - dynamodb:UpdateItem
        - dynamodb:Scan
        - dynamodb:Query
      Resource:
        - arn:aws:dynamodb:ap-northeast-2:${env:AWS_ACCOUNT_ID}:table/${self:custom.dynamoTableNames.${opt:stage, 'dev'}}
    - Effect: Allow
      Action:
        - sqs:SendMessage
        - sqs:ReceiveMessage
        - sqs:DeleteMessage
        - sqs:GetQueueAttributes
      Resource:
        - arn:aws:sqs:ap-northeast-2:${env:AWS_ACCOUNT_ID}:${self:custom.queueNames.${opt:stage, 'dev'}}

custom:
  s3BucketNames:
    dev: hywep-recruit-raw-dev
    qa: hywep-recruit-raw-qa
    prod: hywep-recruit-raw-prod
  dynamoTableNames:
    dev: hywep-recruit-dev
    qa: hywep-recruit-qa
    prod: hywep-recruit-prod
  queueNames:
    dev: hywep-recruit-queue-dev
    qa: hywep-recruit-queue-qa
    prod: hywep-recruit-queue-prod
  elasticsearchDomainName:
    dev: hywep-recruit-es-dev
    qa: hywep-recruit-es-qa
    prod: hywep-recruit-es-prod
  datadog:
    site: ${env:DATADOG_SITE}
    enableXrayTracing: false
    enableDDTracing: true
    enableDDLogs: true
    subscribeToAccessLogs: true
    exclude:
      - dd-excluded-function
    addLayers: true
    monitors:
      - high_error_rate:
          name: "High Error Rate with Modified Warning Threshold"
          message: "More than 10% of the function’s invocations were errors in the selected time range. Notify @data.dog@datadoghq.com @slack-serverless-monitors"
          tags: [ "modified_error_rate", "serverless", "error_rate" ]
          require_full_window: true
          priority: 2
          options:
            include_tags: true
            notify_audit: true
            thresholds:
              warning: 0.05
              critical: 0.1

functions:
  process:
    handler: dist/lambda.handler
    timeout: 600
    memorySize: 1024
    events:
      - sqs:
          arn: arn:aws:sqs:ap-northeast-2:${env:AWS_ACCOUNT_ID}:${self:custom.queueNames.${opt:stage, 'dev'}}
          batchSize: 10

resources:
  Resources:
    HywepRecruitTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.dynamoTableNames.${opt:stage, 'dev'}}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: N
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        StreamSpecification:
          StreamViewType: NEW_IMAGE

  Outputs:
    HywepRecruitStreamArn:
      Description: The ARN of the DynamoDB Stream for HywepRecruitTable
      Value:
        Fn::GetAtt:
          - HywepRecruitTable
          - StreamArn
      Export:
        Name: HywepRecruitStreamArn-${opt:stage, 'dev'}
