service: hywep-recruit-etl

provider:
  name: aws
  runtime: nodejs20.x
  region: ap-northeast-2
  environment:
    RECRUIT_TABLE: ${self:custom.dynamoTableNames.${opt:stage, 'dev'}}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:GetObject
        - s3:PutObject
      Resource:
        - arn:aws:s3:::${self:custom.s3BucketNames.${opt:stage, 'dev'}}/*
    - Effect: Allow
      Action:
        - dynamodb:PutItem
        - dynamodb:BatchWriteItem
        - dynamodb:UpdateItem
        - dynamodb:Scan
        - dynamodb:Query
      Resource:
        - arn:aws:dynamodb:ap-northeast-2:${env:AWS_ACCOUNT_ID}:table/${self:custom.dynamoTableNames.${opt:stage, 'dev'}}

custom:
  s3BucketNames:
    dev: hywep-recruit-raw-dev
    qa: hywep-recruit-raw-qa
    prod: hywep-recruit-raw-prod
  dynamoTableNames:
    dev: hywep-recruit-dev
    qa: hywep-recruit-qa
    prod: hywep-recruit-prod

functions:
  process:
    handler: dist/lambda.handler
    timeout: 600
    memorySize: 1024
    events:
      - s3:
          bucket: ${self:custom.s3BucketNames.${opt:stage, 'dev'}}
          event: s3:ObjectCreated:*
          existing: true
          rules:
            - suffix: .json

resources:
  Resources:
    HywepRecruitTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.dynamoTableNames.${opt:stage, 'dev'}}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: N
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        StreamSpecification:
          StreamViewType: NEW_IMAGE

  Outputs:
    HywepRecruitStreamArn:
      Description: The ARN of the DynamoDB Stream for HywepRecruitTable
      Value:
        Fn::GetAtt:
          - HywepRecruitTable
          - StreamArn
      Export:
        Name: HywepRecruitStreamArn-${opt:stage, 'dev'}
